### ISSUE TITLE
Source code on GitHub?

### ISSUE THREAD

**Issue by TobiasRosskopf** [Weathermann/radolan2map#1]
Is there a plan to migrate the source code from GitLab to GitHub for potential pull requests?

**Comment by Weathermann** [comment]
Hi Tobias,
that sounds interesting!
Do you have any improvements?

Couldn't you do that on Gitlab too?
I would then have to maintain the project in two places.

**Comment by Weathermann** [comment]
finished. Code is now on GitHub too.

**Comment by TobiasRosskopf** [comment]
Nice thx! 👍
