### ISSUE TITLE
Konnte Erweiterung 'radolan2map' nicht laden aufgrund eines Fehlers beim Aufruf der classFactory() Methode 

### ISSUE THREAD

**Issue by martaksx** [Weathermann/radolan2map#11]
Unfortunately after downloading the Plugin it's not loading, same problem with QGIS 3.22 and 3.28, I attach part of the screenshot with the issue described. I will be very grateful for any tips!
![grafik](https://github.com/Weathermann/radolan2map/assets/42750541/8da7ff30-8bad-48c3-a6f3-653f491a1e9f)

**Comment by jamaa** [comment]
There seems to be a conflict with the plugin "QGIS Resource Sharing". To confirm, can you try to disable that plugin and see if the error then disappears?

I am not sure how best to avoid the conflict or which plugin is at "fault".

**Comment by Weathermann** [comment]
Thank you for reporting,
Strange, nothing changed recently. I will test it.

Greetings Mario


Am 16-Oct-2023 13:09:10 +0200 schrieb ***@***.***:
> 
> Unfortunately after downloading the Plugin it's not loading, same problem with QGIS 3.22 and 3.28, I attach part of the screenshot with the issue described. I will be very grateful for any tips!
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

-------------------------------------------------------------------------------------------------
FreeMail powered by mail.de - MEHR SICHERHEIT, SERIOSITÄT UND KOMFORT

**Comment by jamaa** [comment]
The problem is that both radolan2map and "QGIS Resource Sharing" plugins use `sys.path.append()` to add the plugin directory to the list of paths that are searched for imports. Both plugins also have a `gui` module, which is where the conflict arises. Above linked PR #13 would fix this (currently based on v1.6)

**Comment by martaksx** [comment]
Hi, didn't had meanwhile time to test it, but @jamaa suggestion was right. Turning off (or I even deinstalled the "QGIS Resource Sharing" plugin) helped with the issue. Thanks for help!
