### ISSUE TITLE
Additional REGNIE functionality

### ISSUE THREAD

**Issue by jamaa** [Weathermann/radolan2map#2]
> radolan2map only offers rudimentary REGNIE support. This tool is primarily intended for the use of RADOLAN products. It is only able to display the values of REGNIE cells as point layer. If you can improve that...

We at @sydroconsult use Python to read REGNIE data and e.g. convert it to geotiff raster files. It would be nice to have this functionality in the form of a QGIS plugin. What are the future plans for REGNIE-support in this plugin? Does it make sense to integrate additionaly REGNIE functionality (e.g. conversion to raster) in this plugin or would a separate REGNIE plugin be more sensible?

**Comment by jamaa** [comment]
In case it wasn't clear: I am thinking about contributing regnie to raster conversion functionality

**Comment by Weathermann** [comment]
Hello Jamaa,
I think such a functionality can be built into the plugin.
The resulting GeoTIFF could then be displayed directly on the map.
There is also a RADOLAN sum functionality in which the process is probably similar.

It is only important that all program libraries can be called from the QGIS plugin.
Let me know if you have any code to build in.

Regards
Mario

**Comment by jamaa** [comment]
I would love to try and fork the code, implement the functionality and then make a pull request.

I don't have any experience developing QGIS plugins though, maybe you can give some pointers on how best to test the code? Do I just place all the files in the .plugin repository or is there more involved?

**Comment by Weathermann** [comment]
Unfortunately, I am not experienced in testing, especially not with the whole QGIS environment ... I have only ever tested the functionality manually.

Yes, try it or another idea:
if the conversion process doesn't involve too many lines of code and isn't too complicated, I can build it in too.

There are no further dependencies if I understand your question correctly.

**Comment by jamaa** [comment]
Thanks for your offer, but I would like to use this opportunity to get myself acquainted with QGIS plugin development, so I will give it a try myself.

How do you build/package the plugin? Is there any significant difference between the files in the repo and the files in the plugin package? I see e.g. a metadata.txt in the plugin package that is not part of the repo. I guess I can easily copy and adapt that file if it is necessary for QGIS. Any other things I should know?

**Comment by jamaa** [comment]
and one more question: what are your plans for the GitLab repo? I noticed that the GitHub repo does not include the whole commit history, i.e. is not a clone or fork. Why two separate repos and which one should be the main repo for the future? I wouldn't mind using the GitLab repo if you prefer that.

**Comment by Weathermann** [comment]
The Gitlab repo existed first and I always uploaded my updates there.
**The latest version is here on Github.**
I created this repo because there were only requests for extensions here on Github. Nobody was interested in it on Gitlab.
Also I'm here because of some activities in the [Pytroll](https://github.com/pytroll) project.
**So at the moment it looks like the main work is going to take place here :-)** It's OK to work here.

**Comment by jamaa** [comment]
I have started work here: https://github.com/sydroconsult/radolan2map/tree/regnie2raster
So far it can convert daily and monthly regnie files. When you convert to CSV, it does the raster conversion at the same time. I tested with QGIS 3.16 on Win10.
Things I still want to add before I make a pull request: 

- [ ] support for yearly regnie files
- [ ] support for reading gz files directly

Please have a look and see if you are OK with how I implemented it, maybe you also have some ideas about things to add/change?

The new script `regnie2raster.py` can also be called from the commandline (similar to `Regnie2CSV.py`).

Regarding QGIS plugin development, it is easier than I thought. I found https://plugins.qgis.org/plugins/plugin_reloader/ which is supposed to reload a plugin on the fly but for some reason it does not work with radolan2map, I had to restart QGIS everytime I made changes to the code, which is a bit of a nuisance.

**Comment by Weathermann** [comment]
Wow, you are very fast!
I'll check it out, but it'll take some time.

> support for yearly regnie files
> support for reading gz files directly
I think that should work already.

It's good that `regnie2raster.py` also works on the command line.

I know the Plugin Reloader - and yes - it didn't work for me, I always had to restart QGIS. It's time-consuming.
I was wondering if the whole application is maybe too big or there is a problem with the programming. Maybe you will find the mistake :-)

**Comment by jamaa** [comment]
>I think that should work already.

I guess it would if regnie2raster would reuse the routines provided by regnie2csv. But for now, regnie2raster is completely self-contained, i.e. has its own method for reading regnie files. I didn't want to mess too much with the existing code. It does make sense that both scripts use the same methods, though. Perhaps we should have a separate general regnie class for general file handling and reading, which can be used both by regnie2raster and regnie2csv.

**Comment by Weathermann** [comment]
>Perhaps we should have a separate general regnie class for general file handling and reading, which can be used both by regnie2raster and regnie2csv.

Good idea!
Initializes at one place, and after that, one can select the output type by calling the proper method:
```
to_csv()
to_raster()
```
:-)

**Comment by Weathermann** [comment]
I've tried your version, installed the plugin from zip,
it was running, but after REGNIE conversion I got:

![qgis_316_error](https://user-images.githubusercontent.com/60328977/143939570-9be8618d-a935-494a-84f7-9e67e729a858.png)
It seems to be a dependency of numpy.

I installed QGIS 3.16 Hannover (LTR) on openSUSE 15.3.
From SUSE repo I've never got a version to work for years, so I installed from flatpak (https://flathub.org/apps/details/org.qgis.qgis).

I can try a command line call.

**Comment by Weathermann** [comment]
Hm, installed a newer `libgeotiff` (not from package manager) and I get another error:
`ImportError: /usr/lib64/libgdal.so.29: undefined symbol: opj_encoder_set_extra_options`

I think, I can try it on Windows with an older QGIS, but ...

**Comment by Weathermann** [comment]
Wow, on Windows it works!
TIFF was created and loaded, and the TIFF file is visible in the regnie conversion folder.
Very good!
So I should catch the error occurring on faulty GDAL installations on Linux.

![regnie2raster_windows](https://user-images.githubusercontent.com/60328977/144265564-8dd5263e-1643-45f2-89f4-ac60f58c8306.jpg)

**Comment by Weathermann** [comment]
Should we assign a QML color palette automatically after loading?
Can you produce something like that?

**Comment by jamaa** [comment]
Sorry I can't help with the Linux issue. GDAL for Python is such a pain to install properly on Windows, I always thought it would be easier on Linux. I guess not :-)

On Windows, I believe QGIS is installed with its own Python instance including all the GDAL stuff, so as long as you use the plugin from within QGIS, you should never have a problem. Or at least you don't have to deal with the GDAL installation yourself. Is it different on Linux?

A predefined color palette using a QML, why not. All other layers get one as well, so it would be consistent in that regard. If you have one (or several for the different timescales I guess), you can give it to me and I'll integrate them in my branch. Or I can also create some myself.

**Comment by Weathermann** [comment]
I added your code in my project.
I used git commands so you can follow the changes.
I also removed the hint on the REGNIE tab that rasterizing is missing :-)
Added REGNIE raster legends for daily, monthly, yearly.
There is something more to do but for now...

I think, I can include compatibility for gz format and Path objects.

**Comment by jamaa** [comment]
>I added your code in my project.

Great!
>I used git commands so you can follow the changes.

Just wondering, why didn't you pull from my branch and implement your additional changes on top of my commits? If I want to continue contributing, I guess I now have to pull your commits and discard mine? Not a big problem I guess, but this makes collaboration a bit cumbersome and also the authorship of my commits is lost.

**Comment by jamaa** [comment]
I tested your version and it works fine for me on Win10 QGIS 3.16. 

I noticed that the CSV file is generated, but not added as a layer, which takes unnecessary time. If you want to keep the statistics output, why not use the the numpy array returned from the ```regnie2raster.regnie2array()``` to calculate the statistics? It should be substantially faster. This also plays in to our previous idea of having a centralized regnie module/class. Do you want me to start working on that or have you already started?

**Comment by Weathermann** [comment]
> Just wondering, why didn't you pull from my branch and implement your additional changes on top of my commits? If I want to continue contributing, I guess I now have to pull your commits and discard mine? Not a big problem I guess, but this makes collaboration a bit cumbersome and also the authorship of my commits is lost.

It was not my intention to diminish your contribution or to let it go under! I apologize for that.
I don't know exactly why I did it that way. At first I thought about developing on your branch, but I wasn't 100% sure whether all resources are really included here, then pull requests arise with you and then a second project will result from it.
I only learned something about the Git commands yesterday and the interaction between the local project and GitHub. It will get better in the future. Our collaboration helps me to learn more about Git*
You are welcome to add yourself as an author to the metadata file!

I think we can forego creating the CSV altogether or just have it created as a fallback if the GDAL problem occurs. 

I can't move on until the middle of next week so feel free to keep working on this.
But you must now make a new fork.

**Comment by jamaa** [comment]
It's OK. I understand it wasn't ill-intentioned on your side. 

I pulled your commits to my existing fork and started a new branch: https://github.com/sydroconsult/radolan2map/tree/regnie where I started refactoring the regnie stuff. There is now a central `Regnie` class for general functionality which `regnie2raster` and `Regnie2CSV` can both use. For now, the only really useful method is `to_array()`. I then rewrote `_convert_to_csv()` to use this array instead of reading from the file itself and I get identical CSV files, so it seems to work. I'm not sute whether it is "better" or the code more understandable this way but I think it is useful to have only one method for actually reading the regnie file, and for now, that is the `to_array()`method. 

We could now move other functionality from `Regnie2CSV` to the `Regnie` class, such as gz handling etc., so that both conversion modules can profit.

While checking the generated CSV files, I noticed that the IDs do not correspond to the official IDs provided by DWD here: https://opendata.dwd.de/climate_environment/CDC/grids_germany/daily/regnie/Regnie2GIS/regnie-polygon.zip
In the DWD shapefile, only valid cells have an ID, so ID 1 is the first top-left cell with data, somewhere in Sylt. (This has never made sense to me, but that's the way it is.) So in order to allow joining the CSV with the DWD polygon-shapefile we need to change the way in which IDs are counted in `Regnie2CSV`. Or is there something I'm missing?

How about we let the user decide whether they want CSV or raster?

**Comment by Weathermann** [comment]
I understood the whole CSV generation and joining with a shapefile as a workaround, since the rasterization did not exist.
Does the user have any advantage with the CSV format?

I have the feeling that you are very fit with Regnie and Numpy functions, so just get started :-)
It's wonderful that things are progressing so well now and that I no longer have to do everything alone! :-)

**Comment by jamaa** [comment]
You are right, CSV is not really useful anyway. I have now added support for gzip and multiannual Regnie files, rearranged the code a bit and removed CSV functionality completely.

BTW, and this caused me quite a headache: did you know that some cells in `RAS9120.JAH` from https://opendata.dwd.de/climate_environment/CDC/grids_germany/multi_annual/regnie/9120.tar have negative values? Not -999 but e.g.  -99, -181, -225, -104, -157, -231. As only -999 is considered an error value, this results in some weird statistics, which threw me off, but the data is read correctly.

Anyway, I think it is complete now? Let me know if you have any suggestions for changes. I can also create a GitHub pull request if you want, that should allow you to easily integrate my commits and allow you to make further changes on top of them.

**Comment by Weathermann** [comment]
You are right, that's strange.
I inquire, whether it is a mistake.

**Comment by Weathermann** [comment]
Yes, it has been confirmed as a bug.
The data will be recalculated and until then you should interpret these values as missing values.

**Comment by jamaa** [comment]
I think it is better that the plugin shows those erroneous values than to treat them as missing, at least the user can then see that are errors in the data.

**Comment by Weathermann** [comment]
After the correction calculation, such values should no longer appear anywhere (the faulty grids will be replaced).
The problem arose from incorrect daily values from a station, which had an impact on the climatological calculation.
Should one then make an effort to recognize such values?

**Comment by jamaa** [comment]
Do you mean whether a warning should be displayed in radolan2map when it encounters negative values? I don't think so. After all, it is not a plugin for validating REGNIE data, just for converting and displaying it. There could be other errors in the data that the plugin can't even detect. In my opinion, it is enough that radolan2map shows the statistics, such blatant errors such as negative values will show up there.

Since you seem to have such a good connetion to the DWD :-) : I have noticed that sometimes, older daily and monthly REGNIE gets updated on the DWD server and I have always wondered why and whether there is a place where such retroactive changes are documented?

**Comment by Weathermann** [comment]
I think we've now integrated all of the new functionality. :+1: 
Should we package this as a plugin version 1.6 and upload it?

**Comment by jamaa** [comment]
Please do! :-) Or tell me what I can do to help with that

**Comment by Weathermann** [comment]
I've uploaded the plugin to
https://plugins.qgis.org/plugins/radolan2map/
Version 1.6 now.
But we still have to wait for the approval of the plugin (QGIS-Devs), I have no influence on that.
Great work!

**Comment by jamaa** [comment]
Great! It's been a pleasure! If the QGIS Devs want any changes, I'll be glad to help.

**Comment by Weathermann** [comment]
the corrected multiannual file was uploaded yesterday:
https://opendata.dwd.de/climate_environment/CDC/grids_germany/multi_annual/regnie/

**Comment by Weathermann** [comment]
The plugin has finally been approved!
https://plugins.qgis.org/plugins/radolan2map/version/1.6/
